### ISSUE TITLE
Scrobble Lexicon Definition

### ISSUE THREAD

**Issue by mmattbtw** [teal-fm/teal#13]
should include, time, musicbrainz ids

**Comment by espeon** [comment]
thinking about embedding images in this. probably not ideal as we can just get them from the MBID if available, but that's an extra call.

**Comment by kjloveless** [comment]
> thinking about embedding images in this. probably not ideal as we can just get them from the MBID if available, but that's an extra call.

we can/should probably put art on the burner for now while we pick at how exactly bsky is storing thum blobs already

**Comment by espeon** [comment]
#27 should close this 🙂
